# Change these first
owner: pasilobus # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Cloud
    url: https://www.pasilobus.com
  - name: Comity
    url: https://www.comity.app
  - name: Cybarmor
    url: https://www.cybarmor.app
  - name: ShopXR
    url: https://www.shopxr.app
  - name: Offerbox
    url: https://www.offerbox.app

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pasilobus.com
  # baseUrl: /your-repo-name
  logoUrl: https://www.pasilobus.com/apple-touch-icon.png
  favicon: https://www.pasilobus.com/favicon-32x32.png
  name: Pasilobus Status
  introTitle: "**Pasilobus** system status"
  introMessage: The current status and history of Pasilobus platform services.
  navbar:
    - title: Status
      href: /
    - title: Contact
      href: https://pasilobus.com/contacts/new

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: We code to make commerce better
